# 站点信息
site_name: 技术宅入门指南
site_description: 给所有人的计算机通识课
site_author: fzf404
site_url: https://share.fzf404.top/
# 仓库信息
repo_name: fzf404/share
repo_url: https://github.com/fzf404/share
edit_uri: edit/master/docs/

copyright: Copyright &copy; 2021 By 你们的小f

# 主题
theme:
  name: material
  logo: "assets/logo.png"
  favicon: assets/logo.png
  palette:
    - scheme: slate 
      primary: deep purple
      accent: orange      
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: default
      primary: deep purple
      accent: orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  language: "zh"
  features:
    - navigation.tabs
    - navigation.top
  font:
    text: Noto Sans
    code: Source Code Pro

# 插件
plugins:
  - search
  - minify:
      minify_html: true

# Markdown扩展
markdown_extensions:
  - admonition # 注意
  - pymdownx.details # 折叠注意
  - pymdownx.superfences # 注意中嵌套代码和内容块
  - pymdownx.highlight # 代码高亮

# 扩展
extra:
  homepage: https://www.fzf404.top
